task: detection
evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 11          # confirm with the command above
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /srv/data1/Salim/Underwater/RUOD/RUOD_pic/train
    ann_file: /srv/data1/Salim/Underwater/RUOD/RUOD_ANN/instances_train.json
    return_masks: False
    transforms: {type: Compose, ops: ~}
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn: {type: BatchImageCollateFunction}

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /srv/data1/Salim/Underwater/RUOD/RUOD_pic/test
    ann_file: /srv/data1/Salim/Underwater/RUOD/RUOD_ANN/instances_test.json
    return_masks: False
    transforms: {type: Compose, ops: ~}
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn: {type: BatchImageCollateFunction}